### ISSUE TITLE
BPS: Solution is 'Lorem Ipsum'

### ISSUE THREAD

**Issue by jalbertgagnier** [ObjectiveSubject/obsub#29]
Do we not have copy from our old case study?

**Comment by kpettinga** [comment]
I'm going to need to look at how we can recover the old database.

**Comment by kpettinga** [comment]
Hey @jalbertgagnier, I've recovered the DB from the old site and pasted the content from the BPS project here. Can you let me know what parts of this you want to include in the Solution section of the new BPS case study?
///

**simplifying an anxiety-driving process**

Every year in Boston, 57,000 students must be placed in 137 public schools. The Discover Boston Public Schools project was born out of a 2011 [Code for America](http://www.codeforamerica.org/) fellowship by Joel Mahoney, to address the school department''s critical mandate to engage parents in the process of placing their students in schools. In its first pilot year, upwards of half the parents in Boston used the platform to identify the right school for their child — a pretty remarkable adoption rate for new civic technology.

> "[Discover BPS] changed the way we relate to parents."
> John McDonough, Interim Superintendent, Boston Public Schools

In 2013, the [school district](http://www.bostonpublicschools.org/) enacted a policy to transition from a zone-based model to a home-based model of placement, allowing parents to find the best schools for their children within close proximity to their home. The New York Times [wrote about the genesis of this algorithm](http://www.nytimes.com/2013/03/13/education/no-division-required-in-this-school-problem.html?pagewanted=all).

**complex choices, easy decisions**

To address this policy change, the Discover BPS tool would need to be re-worked. The project team reached out to our team to lead the design of a highly accessible interface that addresses the needs of key constituents with a map-driven interface, centering school options around the location entered by the user.

Key to the solution was to ensure that standardized test scores alone did not lead user selection of schools. To that effect, we emphasized an extensive list of school characteristics that might play a critical role in a parent''s choice. By viewing schools options with preferences such as ''focus on the arts,'' ''full-time nurse,'' specific care hours or facilities, parents are empowered to find the schools that are the right fit for their student.

**branding a process**

With a full understanding of all that the tool needed to accomplish, our team considered how parents would learn about Discover BPS. In the first incarnation of the tool, the initiative had been branded as an individual product, with little to no relationship with the school district.

Since the role of this tool is to serve as the first step in part of the larger registration process, we proposed branding the process holistically, using the bright blue of Boston Public Schools as the unifying element for a streamlined visual system. This cohesive system will play an integral part in the communications campaign to parents.

In addition to helping parents take control of an important decision in the children''s life, rethinking  the user experience represents an opportunity to position Boston Public School as a proactive, innovative and trustworthy organization. A positive perception of the school district can only engender more goodwill and participation from parents, students, and the community alike.

Celebrated online urban policy publication Next City wrote about the project and our involvement in this November 2013 piece: [How Boston Is Building the Hotels.com of Public Schools](http://nextcity.org/sharedcity/entry/how-boston-is-building-the-hotels.com-of-public-schools)

**Comment by jalbertgagnier** [comment]
moving last paragraph intro solution, and added the link reference. 

should look something like this:

**branding a process**
With a full understanding of all that the tool needed to accomplish, our team considered how parents would learn about Discover BPS. In the first incarnation of the tool, the initiative had been branded as an individual product, with little to no relationship with the school district.

Since the role of this tool is to serve as the first step in part of the larger registration process, we proposed branding the process holistically, using the bright blue of Boston Public Schools as the unifying element for a streamlined visual system. This cohesive system will play an integral part in the communications campaign to parents.

~~In addition to helping parents take control of an important decision in the children''s life, rethinking the user experience represents an opportunity to position Boston Public School as a proactive, innovative and trustworthy organization. A positive perception of the school district can only engender more goodwill and participation from parents, students, and the community alike.~~

**solution**

In addition to helping parents take control of an important decision in the children''s life, rethinking the user experience represents an opportunity to position Boston Public School as a proactive, innovative and trustworthy organization. A positive perception of the school district can only engender more goodwill and participation from parents, students, and the community alike.

Celebrated online urban policy publication Next City wrote about the project and our involvement in this November 2013 piece: [How Boston Is Building the Hotels.com of Public Schools](http://nextcity.org/sharedcity/entry/how-boston-is-building-the-hotels.com-of-public-schools)
