### ISSUE TITLE
Mockup non-collapsed menu

### ISSUE THREAD

**Issue by jalbertgagnier** [ObjectiveSubject/obsub#49]
Hey @kpettinga , (And @elliotarthur too!)

I talked with Emma this weekend and she told me how she wished we still talked about our other projects, and I was: but they are there! And turns out she didn't think of scrolling past. I'm willing to guess she's not alone [also willing not to guess if we can capture that info?]

I think this might be an opportunity to integrate what we talked about, a visible navigation, that moves away upon scroll but allows you to see:
[projects] [clients] [about] [contact] 

Or something like that. 

Furthermore, I'm thinking at the bottom of the page, it might make sense to have larger [About] and [Contact] boxes to click on.

@kpettinga do you think you could mock this up on the dev server?

**Comment by kpettinga** [comment]
Hey @jalbertgagnier are you thinking about a visible navigation that's _separate_ from our existing one contained within the hamburger menu? Or is it that the nav items that are normally contained inside the hamburger menu are visible with no hamburger icon on page load?

I feel like we need to determine which problem we're trying to solve here:
- Do we want to inform users there's more information below the case study cards? 
- OR is it that we want to display the architecture of the site up front by revealing the pages that are normally hidden inside the hamburger menu?
  Perhaps it's both. 

I feel like a simple page nav (vertically aligned dots, for instance, fixed to the right of the page) would work well to inform users that there's a series of sections on the home page.

Maybe we can chat strategy here tomorrow morning?

**Comment by elliotarthur** [comment]
Hi @jalbertgagnier @kpettinga,

I've had a little re-work on the navigation and how this should look on the homepage. 

Firstly I've condensed the main nav to [profile and contact], then moved the case studies and clients links below the main paragraph.

My thoughts behind this is, the collapsed menu is the navigation for the site.However we're adding navigation for the in-page too. Since we've been using in-page navigation on the case studies, it seemed logical to include it on the homepage for the case sudy cards and remaining clients.

For this to happen I jigged the paragraph to allow a little more room for those links.

The size of the type is the same size we're using for all Futura instances. 

@kpettinga could the menu items swip right on scroll rather than down, so it aligns with the entrance tween of the hamburger? Sometimes i get a clash of menu and header which feels awkward. 

![os web design nav 20160301 ewa_home copy 5](https://cloud.githubusercontent.com/assets/12611145/13440577/ae311eca-dfc0-11e5-81ff-a84dcbfa892c.jpg)

**Comment by kpettinga** [comment]
This is up on the staging site now.

**Comment by jalbertgagnier** [comment]
Question for @elliotarthur https://github.com/elliotarthur : since the client scrolls down past the case studies, shouldn’t case studies either
a) also simply scroll down?
b) have the case studies link to the actual pages, rather than down?

I’m leaning towards a).

**Comment by elliotarthur** [comment]
Yeah, I agree. a)
